name: api

networks:
  api_network:
    name: api_network

services:
  mysql:
    container_name: api_mysql
    image: mysql:8.4.2
    networks:
      - api_network
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${DOCKER_COMPOSE_DATA_FOLDER}/mysql-test:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306